name: Test Matrix

on:
  pull_request:
    branches: [main, dev]
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_bandsy
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup test database
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          CLERK_SECRET_KEY: test_secret_key
          CLERK_WEBHOOK_SIGNING_SECRET: test_webhook_secret
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: test_publishable_key
          UPLOADTHING_TOKEN: test_uploadthing_token
          NODE_ENV: test
        run: |
          npm run db:push
          npm run db:seed

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          CLERK_SECRET_KEY: test_secret_key
          CLERK_WEBHOOK_SIGNING_SECRET: test_webhook_secret
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: test_publishable_key
          UPLOADTHING_TOKEN: test_uploadthing_token
          NODE_ENV: test
        run: npm run ci:test
